# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  front
  namespace: default
  labels:
    app:  front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  front
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  front
        image:  sopascampeao/front:v2
        imagePullPolicy: Never
        ports:
        - containerPort:  80
          name:  front
      restartPolicy: Always

